### ISSUE TITLE
Issue translation products

### ISSUE THREAD

**Issue by noxs4u** [macopedia/akeneo-openai-translator#2]
Akeneo Versie: CE 7.0.30 Sahara Hare
After doing translations in bulk we got different errors

this is what we see in akeno tasks..
<html>
<body>

Attribute is not editableObject weergeven
--
Attribute is not editableObject weergeven
Attribute is not editableObject weergeven
Property "" does not exist.

</body>
</html>

and here are some logs

[2024-06-05T08:18:40.708258+00:00] app.ERROR: 08:18:40 ERROR     [batch] Akeneo\Tool\Component\StorageUtils\Exception\UnknownPropertyException: Property "<START>" does not exist. in /home/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/StorageUtils/Exception/UnknownPropertyException.php:34 Stack trace: #0 /home/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Updater/PropertySetter.php(52): Akeneo\Tool\Component\StorageUtils\Exception\UnknownPropertyException::unknownProperty() #1 /home/akeneo/pim-community-standard/vendor/macopedia/akeneo-openai-translator/src/Macopedia/OpenAiTranslator/Service/TranslateAttributesService.php(100): Akeneo\Pim\Enrichment\Component\Product\Updater\PropertySetter->setData() #2 /home/akeneo/pim-community-standard/vendor/macopedia/akeneo-openai-translator/src/Macopedia/OpenAiTranslator/Connector/Processor/MassEdit/TranslateAttributesProcessor.php(50): Macopedia\OpenAiTranslator\Service\TranslateAttributesService->translateAttributes() #3 /home/akeneo/pim-community-standard/vendor/macopedia/akeneo-openai-translator/src/Macopedia/OpenAiTranslator/Connector/Processor/MassEdit/TranslateAttributesProcessor.php(28): Macopedia\OpenAiTranslator\Connector\Processor\MassEdit\TranslateAttributesProcessor->translateAttributes() #4 /home/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/Batch/Step/ItemStep.php(183): Macopedia\OpenAiTranslator\Connector\Processor\MassEdit\TranslateAttributesProcessor->process() #5 /home/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/Batch/Step/ItemStep.php(115): Akeneo\Tool\Component\Batch\Step\ItemStep->process() #6 /home/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/Batch/Step/AbstractStep.php(79): Akeneo\Tool\Component\Batch\Step\ItemStep->doExecute() #7 /home/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/Batch/Job/Job.php(252): Akeneo\Tool\Component\Batch\Step\AbstractStep->execute() #8 /home/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/Batch/Job/Job.php(202): Akeneo\Tool\Component\Batch\Job\Job->handleStep() #9 /home/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/Batch/Job/Job.php(126): Akeneo\Tool\Component\Batch\Job\Job->doExecute() #10 /home/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Bundle/BatchBundle/JobExecution/ExecuteJobExecutionHandler.php(62): Akeneo\Tool\Component\Batch\Job\Job->execute() #11 /home/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Bundle/BatchBundle/JobExecution/ExecuteJobExecutionHandler.php(39): Akeneo\Tool\Bundle\BatchBundle\JobExecution\ExecuteJobExecutionHandler->doExecute() #12 /home/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Bundle/BatchBundle/Command/BatchCommand.php(141): Akeneo\Tool\Bundle\BatchBundle\JobExecution\ExecuteJobExecutionHandler->executeFromJobExecutionId() #13 /home/akeneo/pim-community-standard/vendor/symfony/console/Command/Command.php(298): Akeneo\Tool\Bundle\BatchBundle\Command\BatchCommand->execute() #14 /home/akeneo/pim-community-standard/vendor/symfony/console/Application.php(1058): Symfony\Component\Console\Command\Command->run() #15 /home/akeneo/pim-community-standard/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand() #16 /home/akeneo/pim-community-standard/vendor/symfony/console/Application.php(301): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() #17 /home/akeneo/pim-community-standard/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun() #18 /home/akeneo/pim-community-standard/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun() #19 /home/akeneo/pim-community-standard/bin/console(36): Symfony\Component\Console\Application->run() #20 {main} ["exception" => Akeneo\Tool\Component\StorageUtils\Exception\UnknownPropertyException { ...}]  [] []

----------------------

[2024-06-05T08:13:54.218403+00:00] app.ERROR: 08:13:53 ERROR     [batch] Akeneo\Tool\Component\StorageUtils\Exception\UnknownPropertyException: Property "data" does not exist. in /home/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/StorageUtils/Exception/UnknownPropertyException.php:34 Stack trace: #0 /home/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Updater/PropertySetter.php(52): Akeneo\Tool\Component\StorageUtils\Exception\UnknownPropertyException::unknownProperty() #1 /home/akeneo/pim-community-standard/vendor/macopedia/akeneo-openai-translator/src/Macopedia/OpenAiTranslator/Service/TranslateAttributesService.php(100): Akeneo\Pim\Enrichment\Component\Product\Updater\PropertySetter->setData() #2 /home/akeneo/pim-community-standard/vendor/macopedia/akeneo-openai-translator/src/Macopedia/OpenAiTranslator/Connector/Processor/MassEdit/TranslateAttributesProcessor.php(50): Macopedia\OpenAiTranslator\Service\TranslateAttributesService->translateAttributes() #3 /home/akeneo/pim-community-standard/vendor/macopedia/akeneo-openai-translator/src/Macopedia/OpenAiTranslator/Connector/Processor/MassEdit/TranslateAttributesProcessor.php(28): Macopedia\OpenAiTranslator\Connector\Processor\MassEdit\TranslateAttributesProcessor->translateAttributes() #4 /home/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/Batch/Step/ItemStep.php(183): Macopedia\OpenAiTranslator\Connector\Processor\MassEdit\TranslateAttributesProcessor->process() #5 /home/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/Batch/Step/ItemStep.php(115): Akeneo\Tool\Component\Batch\Step\ItemStep->process() #6 /home/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/Batch/Step/AbstractStep.php(79): Akeneo\Tool\Component\Batch\Step\ItemStep->doExecute() #7 /home/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/Batch/Job/Job.php(252): Akeneo\Tool\Component\Batch\Step\AbstractStep->execute() #8 /home/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/Batch/Job/Job.php(202): Akeneo\Tool\Component\Batch\Job\Job->handleStep() #9 /home/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/Batch/Job/Job.php(126): Akeneo\Tool\Component\Batch\Job\Job->doExecute() #10 /home/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Bundle/BatchBundle/JobExecution/ExecuteJobExecutionHandler.php(62): Akeneo\Tool\Component\Batch\Job\Job->execute() #11 /home/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Bundle/BatchBundle/JobExecution/ExecuteJobExecutionHandler.php(39): Akeneo\Tool\Bundle\BatchBundle\JobExecution\ExecuteJobExecutionHandler->doExecute() #12 /home/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Bundle/BatchBundle/Command/BatchCommand.php(141): Akeneo\Tool\Bundle\BatchBundle\JobExecution\ExecuteJobExecutionHandler->executeFromJobExecutionId() #13 /home/akeneo/pim-community-standard/vendor/symfony/console/Command/Command.php(298): Akeneo\Tool\Bundle\BatchBundle\Command\BatchCommand->execute() #14 /home/akeneo/pim-community-standard/vendor/symfony/console/Application.php(1058): Symfony\Component\Console\Command\Command->run() #15 /home/akeneo/pim-community-standard/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand() #16 /home/akeneo/pim-community-standard/vendor/symfony/console/Application.php(301): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() #17 /home/akeneo/pim-community-standard/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun() #18 /home/akeneo/pim-community-standard/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun() #19 /home/akeneo/pim-community-standard/bin/console(36): Symfony\Component\Console\Application->run() #20 {main} ["exception" => Akeneo\Tool\Component\StorageUtils\Exception\UnknownPropertyException { ...}]  [] []

---------------------

[2024-06-05T08:13:53.980972+00:00] app.WARNING: E_WARNING: Undefined array key "data" {"code":2,"message":"Undefined array key \"data\"","file":"/home/akeneo/pim-community-standard/vendor/macopedia/akeneo-openai-translator/src/Macopedia/OpenAiTranslator/Service/TranslateAttributesService.php","line":97} []

[2024-06-05T08:13:53.981140+00:00] app.WARNING: E_WARNING: Undefined array key "data" {"code":2,"message":"Undefined array key \"data\"","file":"/home/akeneo/pim-community-standard/vendor/macopedia/akeneo-openai-translator/src/Macopedia/OpenAiTranslator/Service/TranslateAttributesService.php","line":100} []

**Comment by noxs4u** [comment]
![fout1](https://github.com/macopedia/akeneo-openai-translator/assets/33119147/15ca4491-e3d3-4afb-98f1-14947eb9152c)
![fout2](https://github.com/macopedia/akeneo-openai-translator/assets/33119147/2dc4c2d8-604f-4b10-9225-f373c88b22c0)

**Comment by noxs4u** [comment]
I's not working for a product model with variants

**Comment by piotrmus** [comment]
@noxs4u Thank you for creating this issue. We are working internally on this case.

**Comment by noxs4u** [comment]
@piotrmus thanks.
![image](https://github.com/macopedia/akeneo-openai-translator/assets/33119147/9e6323b1-7d75-4e36-8bd9-eb6aa29bfb29)
![image](https://github.com/macopedia/akeneo-openai-translator/assets/33119147/0af03796-5cc9-4342-876a-b0c87c5f3463)
![image](https://github.com/macopedia/akeneo-openai-translator/assets/33119147/e90a8490-cbe6-40b8-aa39-bdd9e6a43fb9)

The issue is related to families. Because we manage these content on product model level. See images

**Comment by noxs4u** [comment]
![image](https://github.com/macopedia/akeneo-openai-translator/assets/33119147/c41d6a8a-6568-4853-9405-e9d695b77a71)
this is what i get after trying to translate this product

**Comment by ktomaszewski** [comment]
@noxs4u 
Could you please check if the problem still occurs after updating to version **v1.2.2**?

**Comment by ktomaszewski** [comment]
I'm closing this issue because it should be fixed in v1.2.2. If this occurs again, feel free to create a new issue.
